name: Cancel Previous Runs

on:
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - requested

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-20.04
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build_and_test.yml
